version: '2.0'

volumes:
  db: {}

services:
  consul:
    image: consul:1.9.1
    command: ["agent","-dev","-client=0.0.0.0"]
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul/config:/consul/config
      - ./service/config:/service/config
  fabio:
    image: fabiolb/fabio:1.5.15-go1.15.5
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes:
      - ./fabiolb/config:/etc/fabio    
  db:
    image: postgres:13.1
    depends_on: 
      - "consul"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  service_config_loader:
    image: appropriate/curl
    depends_on:
      - "consul"
    volumes:
      - .:/cfg
    command: ["sh","/cfg/load-config.sh","xyz-solution"]
  keycloak:
    image: jboss/keycloak:12.0.1
    depends_on: 
      - "consul"
      - "db"
    command: ["-b","keycloak","-bmanagement","keycloak"]
    #ports:
    #  - "8080:8080"
    #  - "9990:9990"
    volumes:
      - ./security_realms:/security_realms
    environment:
      #JBOSS_HOST: keycloak
      #JAVA_OPTS_APPEND: "-Dkeycloak.frontendUrl=http://keycloak:8080"
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://localhost:9999/auth/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /security_realms/xyz_solution_realm.json
      DB_VENDOR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      DB_ADDR: db
  sf-portal:
    image: sysfoundry/sf-svc-portal:1.0-SNAPSHOT
    ports:
      - "9090:9090"
    depends_on:
      - "consul"
      - "db"
      - "keycloak"
      - "service_config_loader"  
    environment:
      JAVA_TOOL_OPTIONS: "-Disis.security.logout.external=true -Dsf.solution.name=xyz-solution -Dspring.cloud.consul.host=consul"