isis:
  applib:
    annotation:
      action:
        explicit: true
        command: ignore_safe
        publishing: all
      action-layout:
        css-class:
          patterns:
            delete.*:btn-danger,
            discard.*:btn-warning,
            remove.*:btn-warning
      domain-object:
        auditing: all
        publishing: all
      property:
        command: all
        publishing: all

  core:
    meta-model:
      introspector:
        lock-after-full-introspection: true
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true

    runtime-services:
      translation:
        po:
          mode: disabled

  viewer:
    wicket:
      application:
        about: ${isis.viewer.wicket.application.name}
        brand-logo-header: images/apache-isis/logo-48x48.png
        css: css/application.css
        favicon-url: images/favicon.png
        js: scripts/application.js
        name: xyz-solution portal
        menubars-layout-xml: menubars.layout.xml

      credit:
        - url:  http://sysfoundry.org
          image: images/apache-isis/logo-48x48.png
          name: Sysfoundry

      themes:
        show-chooser: true

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true


  persistence:
    jdo-datanucleus:
      impl:
        javax:
          jdo:
            option:
              ConnectionURL: jdbc:postgresql://db:5432/${sf.solution.name}
              ConnectionDriverName: org.postgresql.Driver
              ConnectionUserName: postgres
              ConnectionPassword: postgres
        # note that properties under 'isis.persistence.jdo-datanucleus.impl' are passed through directly
        # to DataNucleus, and use variously camelCase or PascalCase rather than kebab-case
        datanucleus:
          schema:
            validateTables: true
            validateConstraints: true
            autoCreateAll: true

          persistenceByReachabilityAtCommit: false
          identifier:
            case: MixedCase

          cache:
            level2:
              type: none
              mode: ENABLE_SELECTIVE

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  port: 9090
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt
  cloud:
    consul:
      discovery:
        metadata:
          domain: general
          solution-key: ${sf.solution.name}
          has-gui: true
          secure: true
          public-uri: http://localhost:9090/wicket/

keycloak:
  realm: ${sf.solution.name}
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ${sf.solution.name}
  public-client: true
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
